### ISSUE TITLE
Import Geo Performance Report to MongoDB 

### ISSUE THREAD

**Issue by QuadStingray** [googleads/aw-reporting#134]
With the Version in Branch "v201502_upgrade" the Geo Performance Report Import into MongoDB doesn't work. In Master-Branch everything worked fine.

```
2015-05-29 12:25:20,732 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: xxxxxxxxxx java.lang.RuntimeException: java.lang.NumberFormatException: Sign character in wrong position
```

```
Error Parsing column # 5 with contents:  --
Error Parsing PropertyDescriptor: java.beans.PropertyDescriptor[name=metroCriteriaId; propertyType=class java.lang.Long; readMethod=public java.lang.Long com.google.api.ads.adwords.awreporting.model.entities.ReportGeo.getMetroCriteriaId(); writeMethod=public void com.google.api.ads.adwords.awreporting.model.entities.ReportGeo.setMetroCriteriaId(java.lang.Long)]
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: Sign character in wrong position
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:143)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: Sign character in wrong position
	at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:122)
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:55)
	... 6 more
Caused by: java.lang.NumberFormatException: Sign character in wrong position
	at java.lang.Long.decode(Long.java:917)
	at com.sun.beans.editors.LongEditor.setAsText(LongEditor.java:45)
	at au.com.bytecode.opencsv.bean.CsvToBean.convertValue(CsvToBean.java:82)
	at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:102)
	... 7 more
```

Selected Fields from "report.properties"
```
GEO_PERFORMANCE_REPORT=ExternalCustomerId, CampaignId, RegionCriteriaId, MetroCriteriaId, CountryCriteriaId, CityCriteriaId, Cost, Clicks, Impressions, AverageCpc, IsTargetingLocation, AdNetworkType2, LocationType, Year, Month, Week, Date
```

**Comment by chenzhuo914** [comment]
It seems the data returned from AdWords report is wrong. In v201409 the MetroCriteriaId is of type String, and in v201502 it changed to Long. I guess AdWords report returns some value that is not convertible to Long.

Could you try to narrow down the problem to some minimal reproducible example, and check which MetroCriteriaId data is indeed incorrect? You can send us the account ID and date range of problematic report, and we will check with AdWords report to find out what's wrong there.

**Comment by QuadStingray** [comment]
Hi,

- startDate 20150501
- endDate  20150531

It seems to be wrong in all of our accounts. How can I send you my account id for your tests?

**Comment by QuadStingray** [comment]
I changed my "report.properties" and i have the same error for this fields:
- RegionCriteriaId
- MetroCriteriaId
- CityCriteriaId

**Comment by juliantoledo** [comment]
We should download a large group of reports to make sure the IDs are indeed Longs, there was a bug on the GeoReport in the past where the IDs were a mix of Longs and Strings.

**Comment by QuadStingray** [comment]
No I got the same error for MySQL. 

I think this is an error in the Java by parseing the API Response to Java-Object.
```
java.lang.NumberFormatException: Sign character in wrong position
```

**Comment by chenzhuo914** [comment]
Hi QuadStingray, the error is at parsing logic, but it's more likely the underlying data is the culprit. So besides the start/end date, please also give your Account ID, so I can reproduce the issue and find someone to fix it. Thanks!

**Comment by QuadStingray** [comment]
Can you give me an eMailadress, than I can send you the account Id.

**Comment by chenzhuo914** [comment]
chenzhuo914@gmail.com
Please send both MCC ID and the account ID that encounters this issue.

**Comment by chenzhuo914** [comment]
Hi QuadStingray, it turns out that those Geo IDs (CityCriteriaId, CountryCriteriaId, MetroCriteriaId, MostSpecificCriteriaId, RegionCriteriaId) are using "==" as empty values (as explained in this doc: https://developers.google.com/adwords/api/docs/guides/reporting-concepts#two-dashes), therefore they cannot always be parsed to Long type.

I've fixed the code by changing the IDs' type to String. Please sync the code and drop your DB table (aw-reporting will regenerate it with corrected column type), and try again.
