### ISSUE TITLE
Error processing file CRITERIA_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by spospy** [googleads/aw-reporting#166]
When running the monthly reports e.g.

java -Xmx4g -jar aw-reporting.jar -startDate 20150701 -endDate 20150731 -file ../monthly-reports-for-pdfs.properties -verbose

an error occurs when generating the CRITERIA_PERFORMANCE_REPORT - "Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'CRITERIA' at row 7"

Here is the entire output of this report:

** Generating: CRITERIA_PERFORMANCE_REPORT **
2015-08-19 11:54:36,904 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile]  Downloading reports...
2015-08-19 11:54:36,904 [INFO|com.google.api.ads.adwords.awreporting.processors.ReportProcessor|ReportProcessor] Instantiate report definition for CRITERIA_PERFORMANCE_REPORT with includeZeroImpressions=false
2015-08-19 11:55:41,416 [INFO|com.google.api.ads.adwords.awreporting.downloader.MultipleClientReportDownloader|MultipleClientReportDownloader]
 Downloaded reports for 3019 accounts in 64 s. 0 failures:

2015-08-19 11:55:41,417 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile]  Processing reports...
2015-08-19 11:56:32,938 [ERROR|com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile|RunnableProcessorOnFile] Error processing file: /tmp/reportDownload-CRITERIA_PERFORMANCE_REPORT-5356546086-918861873090810821.report
org.hibernate.exception.DataException: could not perform addBatch
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:135)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:114)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.addToBatch(BatchingBatch.java:87)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3067)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3509)
        at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:88)
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:364) 
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:356)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:277)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:328)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1234)
        at com.google.api.ads.adwords.awreporting.model.persistence.sql.SqlReportEntitiesPersister.persistReportEntities(SqlReportEntitiesPersister.java:90)  
        at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy21.persistReportEntities(Unknown Source)
        at com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile.run(RunnableProcessorOnFile.java:149)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'CRITERIA' at row 7
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1469)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1071)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:110)
        ... 27 more
2015-08-19 11:57:29,482 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] *** Finished processing all reports in 108 seconds ***

**Comment by chenzhuo914** [comment]
> java.sql.BatchUpdateException: Data truncation: Data too long for column 'CRITERIA' at row 7
The error message is quite informative. Could you try to debug (such as setting breakpoint at the relevant code) to see what's the account in problem, and what's the actual data at row 7 column 'CRITERIA'?

**Comment by chenzhuo914** [comment]
I'm closing this bug since there's no reply for a while, please feel free to reopen it.
