### ISSUE TITLE
Getting "unexpected error accessing the API" in a code that was working fine

### ISSUE THREAD

**Issue by jaison-directi** [googleads/aw-reporting#174]
Getting unexpected error accessing the API in a code that was working fine till 2015-09-03 18:34:05

I suspect there is an issue with the adwords api at the moment. Unfortunately, since I don't have a specific error thrown by the adwords API itself I am unable to communicate the issue on the adwords api forum.

Please check if the issue is reproducible at your end and if so please mention the adwords API error (assuming this is an error at the Adwords API).

The report configuration I'm using is the same as provided in issue #168.

##### output:
2015-09-04 12:57:06,888 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using properties file: /home/jaison/Desktop/reports/aw-reports.properties
2015-09-04 12:57:06,923 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using SQL DB configuration properties.
2015-09-04 12:57:06,924 [WARN|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Updating database schema, this could take a few minutes ...
2015-09-04 12:57:06,924 [WARN|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Done.
2015-09-04 12:57:06,925 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using ONMEMORY Processor.
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2015-09-04 12:57:07,627 [INFO|com.google.api.ads.adwords.awreporting.util.DynamicPropertyPlaceholderConfigurer|PropertiesLoaderSupport] Loading properties file from file [/home/jaison/Desktop/reports/aw-reports.properties]
2015-09-04 12:57:10,235 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Starting report download for dateStart: 20150904 and dateEnd: 20150904
2015-09-04 12:57:10,235 [INFO|com.google.api.ads.adwords.awreporting.processors.onmemory.ReportProcessorOnMemory|ReportProcessorOnMemory] *** Retrieving account IDs ***
2015-09-04 12:57:10,235 [INFO|com.google.api.ads.adwords.awreporting.processors.ReportProcessor|ReportProcessor] Account IDs being recovered from the API. This may take a while...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2015-09-04 12:57:13,486 [INFO|com.google.api.ads.adwords.awreporting.util.ManagedCustomerDelegate|ManagedCustomerDelegate] Retrieving next 1000 accounts.
2015-09-04 12:57:14,654 [INFO|com.google.api.ads.adwords.awreporting.util.ManagedCustomerDelegate|ManagedCustomerDelegate] 49 accounts retrieved.
2015-09-04 12:57:14,654 [ERROR|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Unexpected error accessing the API: null
java.lang.NullPointerException
	at com.google.api.ads.adwords.awreporting.util.ManagedCustomerDelegate.getAccountIds(ManagedCustomerDelegate.java:86)
	at com.google.api.ads.adwords.awreporting.processors.ReportProcessor.retrieveAccountIds(ReportProcessor.java:103)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.ReportProcessorOnMemory.generateReportsForMCC(ReportProcessorOnMemory.java:108)
	at com.google.api.ads.adwords.awreporting.AwReporting.main(AwReporting.java:189)

**Comment by QuadStingray** [comment]
We have the same Problem with our existing (not changed) Version of aw-reporting and config-file.

**Comment by davidbotella** [comment]
Current issue with the ManagedCustomer.canManageClients(). cf : https://groups.google.com/forum/#!topic/adwords-api/GNwK5j0So4Q

**Comment by ashishodia** [comment]
We have same issue here. Below is the errors:


2015-09-04 08:39:39,624 [ERROR|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Unexpected error accessing the API: null
java.lang.NullPointerException
        at com.google.api.ads.adwords.awreporting.util.ManagedCustomerDelegate.getAccountIds(ManagedCustomerDelegate.java:86)
        at com.google.api.ads.adwords.awreporting.processors.ReportProcessor.retrieveAccountIds(ReportProcessor.java:104)
        at com.google.api.ads.adwords.awreporting.processors.onmemory.ReportProcessorOnMemory.generateReportsForMCC(ReportProcessorOnMemory.java:108)
        at com.google.api.ads.adwords.awreporting.AwReporting.main(AwReporting.java:189)

**Comment by chenzhuo914** [comment]
Thanks for reporting this error. The AdWords API engineers are aware of it and working on the fix. We will update this field once there's any more info to share.

**Comment by irfany** [comment]
Hi,

It seems ManagedCustomerDelegate line 86:

       if (!account.isCanManageClients()) {

is returning null values. I have commented the line and its working. Hopefully Google API engineers will fix this issue quickly.

Thanks
Irfan

**Comment by gustavo-moreira** [comment]
The API fix was pushed to production, please try again.
Thanks.

**Comment by irfany** [comment]
Yes, works now, thanks!

**Comment by ashishodia** [comment]
Yes, Working Fine. Thanks for your support guys.
