### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException

### ISSUE THREAD

**Issue by BradRuderman** [googleads/aw-reporting#178]
I am trying to run this utility, on a Mac OS X 10.9.

```
➜  ~  java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```
When using the release or building using maven. I receive the following error:
```
java -Xmx1G -jar aw-reporting/target/aw-reporting.jar -startDate 20150101 -endDate 20150909 --file aw-report.properties -verbose
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
	at java.lang.Class.getMethod0(Class.java:2813)
	at java.lang.Class.getMethod(Class.java:1663)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more
```

I know the issue is related to something is wrong with the class path on my local computer, however please let me know how I can include the correct class path so the dependencies are loaded properly.

**Comment by BradRuderman** [comment]
@gustavo-moreira  any ideas?

**Comment by gustavo-moreira** [comment]
Hi Brad,

did you build the project including all the dependencies in the jar?
mvn compile dependency:copy-dependencies package

Att.

**Comment by chenzhuo914** [comment]
Closing this issue since there's no reply for 17 days. Please feel free to reopen if necessary.
