### ISSUE TITLE
Error in processing Geo Performance Reports for accounts with no Campaigns under them

### ISSUE THREAD

**Issue by jaison-directi** [googleads/aw-reporting#187]
I get "Problem sending data to report download server" error when pulling Geo Performance Reports.

The error is observed for two adwords accounts having ids 4352633759 and 1636733224.
I suspect that the error is due to the fact that these accounts have no Campaigns created under them.

Error:

2015-09-24 10:11:07,939 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: 4352633759 Problem sending data to report download server.
com.google.api.ads.adwords.lib.utils.ReportException: Problem sending data to report download server.
	at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelper.downloadReport(AdHocReportDownloadHelper.java:95)
	at com.google.api.ads.adwords.lib.utils.v201506.ReportDownloader.downloadReport(ReportDownloader.java:84)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.getReportInputStream(RunnableProcessorOnMemory.java:206)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.sun.net.ssl.internal.ssl.InputRecord.readFully(Unknown Source)
	at com.sun.net.ssl.internal.ssl.InputRecord.read(Unknown Source)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at com.sun.net.ssl.internal.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelper.downloadReport(AdHocReportDownloadHelper.java:79)
	... 6 more

**Comment by chenzhuo914** [comment]
I tried with the account IDs you mentioned, and succeeded to download the Geo Performance Report, though the result is empty. I guess this "Problem sending data to report download server" is a transient error, could you try again and see if this error persists?

FYI my log:
>2015-10-08 12:12:28,305 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using properties file: ../../aw-report-sample.properties
>2015-10-08 12:12:28,313 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using accounts file: ../../accountIds.txt
>2015-10-08 12:12:28,417 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using SQL DB configuration properties.
>2015-10-08 12:12:28,417 [WARN|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Updating database schema, this could take a few minutes ...
>2015-10-08 12:12:28,417 [WARN|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Done.
>2015-10-08 12:12:28,419 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Using ONFILE Processor.
>log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
>log4j:WARN Please initialize the log4j system properly.
>log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
>2015-10-08 12:12:29,520 [INFO|com.google.api.ads.adwords.awreporting.util.DynamicPropertyPlaceholderConfigurer|PropertiesLoaderSupport] Loading >properties file from file [/Users/zhuoc/Documents/workspace/aw-reporting/aw-reporting/../../aw-report-sample.properties]
>2015-10-08 12:12:32,963 [INFO|com.google.api.ads.adwords.awreporting.AwReporting|AwReporting] Starting report download for dateStart: 20150910 and >dateEnd: 20150915
>2015-10-08 12:12:32,963 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] *** Retrieving >account IDs ***
>2015-10-08 12:12:32,964 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] Accounts loaded from >file.
>2015-10-08 12:12:33,315 [INFO|com.google.api.ads.adwords.awreporting.processors.ReportProcessor|ReportProcessor] Property includeZeroImpressions=false
>2015-10-08 12:12:33,317 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] *** Generating >Reports for 2 accounts ***
>2015-10-08 12:12:33,325 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] 
>
> ** Generating: GEO_PERFORMANCE_REPORT **
>2015-10-08 12:12:33,325 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile]  Downloading reports...
>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
>SLF4J: Defaulting to no-operation (NOP) logger implementation
>SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>2015-10-08 12:12:36,193 [INFO|com.google.api.ads.adwords.awreporting.downloader.MultipleClientReportDownloader|MultipleClientReportDownloader] 
> Downloaded reports for 2 accounts in 2 s. 0 failures:
>
>2015-10-08 12:12:36,193 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile]  Processing reports...
>2015-10-08 12:12:36,220 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] *** Finished >processing all reports in 0 seconds ***
>
>2015-10-08 12:12:36,220 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] 
> Deleting temporary report files after Parsing...
>2015-10-08 12:12:36,221 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] 
> ** Finished: GEO_PERFORMANCE_REPORT **
>2015-10-08 12:12:36,221 [INFO|com.google.api.ads.adwords.awreporting.processors.onfile.ReportProcessorOnFile|ReportProcessorOnFile] *** Finished processing all reports in 2 seconds ***

**Comment by jaison-directi** [comment]
I do get this error regularly. However, it does not affect the pulling of geo reports of other accounts. I can ignore this error for now.

**Comment by chenzhuo914** [comment]
What do you mean by "regularly"? Is it always happening, or from time to time?

**Comment by jaison-directi** [comment]
It happens from time to time but not every time

**Comment by chenzhuo914** [comment]
Then it seems like some transient error, such as network unstable. I'm afraid there's no much we can do at aw-reporting side, so I'm closing this bug. Please feel free to reopen it if you think otherwise.
