### ISSUE TITLE
not possible to add multiple configurations of the same type of report per file

### ISSUE THREAD

**Issue by dl-wkda** [googleads/aw-reporting#211]
We want to download two versions of the same type of report. However, we are running into error messages, when trying to add a unique identifier to the second report.

As stated in https://goo.gl/OKgzAb :

"The report definition supports multiple configurations of the same type of report per file.
To add new definitions for the same report type, just add the '$' symbol after the name of the
report type, and add am unique identifier to it. It is an optional configuration."

We therefore tried to add $CONVERSION to the second query, to write to a different table in our sql schema. 

KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,ConvertedClicks,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,Criteria,CriteriaDestinationUrl,AdGroupId,CampaignId,Status,IsNegative,CampaignName,KeywordMatchType,Impressions,AdGroupId,CpcBid,AdNetworkType1,AdNetworkType2,CriteriaDestinationUrl,FinalUrls,UrlCustomParameters,AdGroup,SearchExactMatchImpressionShare,SearchImpressionShare,SearchRankLostImpressionShare,BounceRate

KEYWORDS_PERFORMANCE_REPORT$CONVERSION=AccountDescriptiveName,CampaignName,AdGroupName,Id,ExternalCustomerId,CreativeDestinationUrl,CreativeFinalUrls,CreativeFinalMobileUrls,ConvertedClicks,ConversionCategoryName,ConversionValue

The first report completes, but for the second one we get the error message: "Error processing report for account: xxxxxxxxxx a different object with the same identifier value was already associated with the session"

2015-11-19 11:43:32,982 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: xxxxxxxxxx a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords#null-20151117-20151118-20151117-20151118]
org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords#null-20151117-20151118-20151117-20151118]
    at org.hibernate.engine.internal.StatefulPersistenceContext.checkUniqueness(StatefulPersistenceContext.java:697)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:296)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:241)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:109)
    at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
    at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:735)
    at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:727)
    at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:723)
    at com.google.api.ads.adwords.awreporting.model.persistence.sql.SqlReportEntitiesPersister.persistReportEntities(SqlReportEntitiesPersister.java:86)
    at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy21.persistReportEntities(Unknown Source)
    at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:158)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gustavo-moreira** [comment]
Hi,

This is happening because there is not enough segmentation in the second report definition. You must specify additional segmentation fields: AccountId, CampaignId, AdGroupId.
The error is that the ID being generated is not unique for the set of rows that were downloaded.

You can take a look at the setId() method that's in the entity definition for more details: https://github.com/googleads/aw-reporting/blob/master/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportKeywords.java

Att.

**Comment by dl-wkda** [comment]
Thank you, that was indeed the problem!

**Comment by dl-wkda** [comment]
actually, there still another related problem. the second keywords_performance_report is overwriting rows of the first one, for the same day. this I think because the row_id is still only being generated from external_customer_id, AccountId, CampaignId, KeywordId, NetworkType, Date.

the second report, segmented by conversioncategoryname, would need some identifying element in the row_id i believe. 

is there a fix for this in the latest awreport version? or do i need to manually modify the way the row_id is being generated?

**Comment by dl-wkda** [comment]
ok i found a solution. so in case someone else has the same problem, here is my solution. problem was i wanted to pull two reports of the same type, (two keywords reports, segmented in different ways) and the second report definition overwrote date from the first report definition. so in the end i was missing crucial data. the reason was that although the two reports were segmented differently, their row_id, which is the primary key, consisted of the same columns (MCC, CampaignId, AdGroupId,KeywordId,NetworkType,Date). So there was no way the two types of report could exist in the same table, as they were sharing the same primary-key logic. the solution is to extend the row_id.

what i did:
1) i went to aw-reporting/aw-reporting-model/src/main/java/com/google/api/ads/adwords/awreporting/model/entities/ReportKeywords.java

2) i found the public void setId() function. 

3) under "// Adding extra fields for unique ID", I added my additional condition which tells the tool: if there is data from my additional report definition, then add something to the row_id to keep it unique.

i for example segmented my second keywords report by conversioncategoryname and added conversioncategoryname to the row_id where conversioncategoryname is not null:

if (this.getConversionCategoryName() != null && this.getConversionCategoryName().length() > 0) {
      this.id += "-" + this.getConversionCategoryName();
    }

so the final function looked like this:

@Override
  public void setId() {
    // Generating unique id after having accountId, campaignId, adGroupId and date
    if (this.getAccountId() != null && this.getCampaignId() != null && this.getAdGroupId() != null
        && this.getKeywordId() != null) {
      this.id = this.getAccountId() + "-" + this.getCampaignId() + "-" + this.getAdGroupId() + "-"
          + this.getKeywordId();
    }

    this.id += setIdDates();

    // Adding extra fields for unique ID
    if (this.getAdNetwork() != null && this.getAdNetwork().length() > 0) {
      this.id += "-" + this.getAdNetwork();
    }
    if (this.getAdNetworkPartners() != null && this.getAdNetworkPartners().length() > 0) {
      this.id += "-" + this.getAdNetworkPartners();
    }
    if (this.getDevice() != null && this.getDevice().length() > 0) {
      this.id += "-" + this.getDevice();
    }
    if (this.getClickType() != null && this.getClickType().length() > 0) {
      this.id += "-" + this.getClickType();
    }
    if (this.getConversionCategoryName() != null && this.getConversionCategoryName().length() > 0) {
      this.id += "-" + this.getConversionCategoryName();
    }
}

This seems to do the trick. Thanks a lot to the aw-reporting team for the great help and the development of this awesome tool!

**Comment by chenzhuo914** [comment]
Hi dl-wkda, your solution is correct! Actually setId() function should include ALL segment fields so that different reports of the same type (but segmented differently) will not have row_id collision. In this case the ReportKeywords' setId() misses some segment fields (like ConversionCategoryName that you've found), for now please just add missing ones when your find them, and we are having some effort to make up all the missing ones in all the report types. :)
