### ISSUE TITLE
Error processing report for account 

### ISSUE THREAD

**Issue by litan1106** [googleads/aw-reporting#220]
[ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: acccount_number java.net.SocketException: Connection reset
java.lang.RuntimeException: java.net.SocketException: Connection reset
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:554)
	at sun.security.ssl.InputRecord.read(InputRecord.java:509)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3066)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at au.com.bytecode.opencsv.CSVReader.getNextLine(CSVReader.java:266)
	at au.com.bytecode.opencsv.CSVReader.readNext(CSVReader.java:233)
	at com.google.api.ads.adwords.awreporting.model.csv.AwReportCsvReader.readNext(AwReportCsvReader.java:167)
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:53)

**Comment by chenzhuo914** [comment]
> java.net.SocketException: Connection reset
This seems to be a network / connection problem. Could you try to re-run it and check if it's reproducible? If so, please provide more details (such as: account id, report to download, fields selected) so we can reproduce and debug. Thanks~

**Comment by chenzhuo914** [comment]
There's no response for a while, so I'm closing this issue now. Feel free to reopen it if necessary.
