### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by draven72** [googleads/aw-reporting#242]
Hi

When running the application I sometimes get the following error:

2016-06-02 16:49:52,270 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: 8496890173 javax.net.ssl.SSLException: SSL peer shut down incorrectly
java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:557)
	at sun.security.ssl.InputRecord.read(InputRecord.java:509)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3067)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at au.com.bytecode.opencsv.CSVReader.getNextLine(CSVReader.java:266)
	at au.com.bytecode.opencsv.CSVReader.readNext(CSVReader.java:233)
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:53)
	... 6 more

It continues to parse the report and doesn't cause the job to fail, but I have been getting it on different MCCs, accounts and reports. 

At the moment I'm investigating a discrepancy between the stats I see in AWQL and from AW Reporting, and this appears to be the most likely reason (apart from universal app campaigns).

Please let me know if you require any further information.

Regards

Ben

**Comment by draven72** [comment]
I've just got the error again, this time on a different account. I ran it this time with Takipi monitoring, so I have additional information available, including the recorded variables. Here is the stack for the error:

SSLException: SSL peer shut down incorrectly
	at java.io.BufferedReader.readLine(boolean)
	at java.io.BufferedReader.readLine()
	at au.com.bytecode.opencsv.CSVReader.getNextLine()
	at au.com.bytecode.opencsv.CSVReader.readNext()
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext()
	at com.google.common.collect.AbstractIterator.tryToComputeNext()
	at com.google.common.collect.AbstractIterator.hasNext()
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run()
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run()
	at java.lang.Thread.run()

**Comment by joeltoby** [comment]
Hi Ben,

Thanks for reporting this. I'll look into this today and keep you posted.

Joel

**Comment by draven72** [comment]
Hi Joel

Thanks for taking a look at this, please let me know if you need any more information.

Regards

Ben

**Comment by joeltoby** [comment]
Hi Ben,

Thank you.  I've not been able to replicate this on my machine, but I have had similar issues with other projects.

- Which Java version are you running?
- Which OS & version?
- Which version of OpenSSL (`$ openssl version`)?

**Comment by draven72** [comment]
Hi Joel

I'm running Java 1.7.0_101 in Ubuntu 14.04.4, and it's OpenSSL 1.0.

I've also cloned a new version of the code from Github and recompiled it, and this time although I still got the errors, I don't think I'm losing any data (I checked 4 out of the million+ campaigns!), but have asked the analytics team to carry out some QA.

On a side note, I also watched your video on improving the efficiency of using the API for reporting, and as a result was able to lose 40+ fields from the various reports and reduce the run time from 28 hours to 11 - one of our companies has 35 MCC accounts! I've got another meeting to discuss removing more reports and fields to bring this down to a more manageable level so it can be run daily.

Regards

Ben

**Comment by joeltoby** [comment]
Hi Ben,

I've just tried to replicate on Ubuntu 14.04 with Java 1.7.0.  I had no issues / errors.  I had issues downgrading to OpenSSL 1.0.0 (which is the one I assume you are referring to) which is unfortunate as I suspect OpenSSL to be one of the likely causes.

Would upgrading to a new OpenSSL version be an option?  Also, is it possible that issue is caused by a proxy on your end?  The fact that it happens sometimes is strange.

I'm glad to hear that the talk was useful - 17 hours is a nice time saving!  Good to hear :)

**Comment by draven72** [comment]
Hi Joel

I've double checked open ssl, and it's showing as 1.01. Unfortunately Ubuntu doesn't change the version number when it updates and applies the patches, and although there's a 1.0.2 version of OpenSSL, the package installer doesn't support it. I did download the new version and compiled and installed it, but the OS is ignoring it and sticking with it's own version - apparently the only way around this is to uninstall the default version but the uninstaller automatically removes any application that uses it and most of the names I don't recognise or know what they do. As I'm not running the production version on my local machine, I'm going to abandon upgrading it for now, and will make sure the production box has at least got the latest version installed.

Thanks for investigating this.

Regards

Ben

**Comment by joeltoby** [comment]
Hi Ben,

I believe 1.01 is fine.  That's what I'm using, and the issues I found online don't seem to affect this version.  Although I haven't found much relating to Java 1.7.0, I have found various issues relating to the cipher suites and the preference order used by some version of openjdks.

I'm going to ask some of my colleagues if they can shed on my light on this issue, but in the mean time, I wonder if it would worth trying a different JDK?

Cheers,

Joel

**Comment by joeltoby** [comment]
@chenzhuo914 

Hi Zhuo,

Do you have any other idea of what may be causing this?  I'm still trying to find a cause.

Cheers,

Joel

**Comment by draven72** [comment]
Hi Joel

I've updated to Oracle JDK 8 (Java version 1.8.0_91-b14) and Ubuntu 15.10 but I'm still getting the SSL error on some accounts. The first error appeared after the job was running for 9 minutes, then another one 2 minutes later, but for the remaining 10 minutes the job ran for there were no further errors.

Regards

Ben

**Comment by chenzhuo914** [comment]
Hi Joel, sorry I never see this problem before, so had no idea now.

Hi Ben, could you run the aw-reporting till completion, and check the log to find whether this error always occurs on the same set of accounts? If so, could you try to pick one such account (by -accountIdsFile option) and try to create a minimal repro?

Regards,
Zhuo

**Comment by draven72** [comment]
Hi Zhuo

The job always completes, and it seems to effect random accounts, so I don't think it's an issue with a particular account.

I'm going away on holiday tomorrow, so won't have access to the code on my work PC for 2 weeks, but I'll try running a minimal report when I get back, and will let you know, I can also run the current file with Takipi (https://www.takipi.com) enabled, so I can provide additional information, should you need it.

Regards

Ben

**Comment by chenzhuo914** [comment]
Hi Ben,

Besides trying Takipi (which I never used before), could you also try the following:

1. SSLException is inherited from IOException, and from the call stack it seems it's thrown in CsvParserIterator.computNext(). Please modify that code to catch SSLException explicitly and record stack trace / diagnostic information.

2. I noticed you are using ONMEMORY processing, could you also try ONFILE processing (in properties file, put "aw.report.processor.type=ONFILE")? Combined with #1, you could find the account ID and it's CSV file in tmp folder, then we can check what's wrong in that CSV file.

And do enjoy your holiday now! :)

Regards,
Zhuo

**Comment by draven72** [comment]
Hi Zhuo

I've re-run the job again after changing the processor.type to ONFILE and it completed without any issues. I did notice that some of the files were over 130MB, so perhaps the issue could be caused by my PC running low on memory?

Regards

Ben

**Comment by chenzhuo914** [comment]
Hi Ben, glad to know that ONFILE works. It does sound like a memory depletion. You can also try to use ONMEMORY with less threads (by reducing aw.report.processor.threads and aw.report.downloader.num.threads in the properties file) and see if it works.

Just out of curiosity, what report and fields are you downloading that results a file over 130MB? Is it a zipped one or unzipped? Anyways it sounds like you've selected too many segment fields, and you may want to review whether all fields are really necessary. Please refer to [this deck](http://www.slideshare.net/supergigas/best-practices-in-reporting) for the reporting best practices.
