### ISSUE TITLE
Exception while using Report Processor type as ONFILE

### ISSUE THREAD

**Issue by GirijaSankar61** [googleads/aw-reporting#247]
Error while trying to run the report using Report Processor Type ONFILE. Works fine when using ONMEMORY. We are facing this issue ever since we are trying to migrate to new API version i.e., v201603 or v201605

2016-06-27 17:25:00 DEBUG[pool-4-thread-1]ads_api_lib,156: Did not load optional configuration ads.properties:r.conf.ConfigurationLoadException: Encountered a problem reading the provided configuration file "ads.properties"!
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromFile(ConfigurationHelper.java:66)
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.createCombinedConfiguration(ConfigurationHelper.java:151)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:67)
	at com.google.api.ads.common.lib.conf.ConfigurationProvider.get(ConfigurationProvider.java:31)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.google.api.ads.adwords.lib.utils.AdWordsInternals.<clinit>(AdWordsInternals.java:36)
	at com.google.api.ads.adwords.lib.utils.ReportRequestFactoryHelper.<init>(ReportRequestFactoryHelper.java:53)
	at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelperImpl.<init>(AdHocReportDownloadHelperImpl.java:47)
	at com.google.api.ads.adwords.lib.utils.AdHocReportDownloadHelper.<init>(AdHocReportDownloadHelper.java:38)
	at com.google.api.ads.adwords.lib.utils.v201605.ReportDownloader.<init>(ReportDownloader.java:54)
	at com.google.api.ads.adwords.awreporting.downloader.RunnableDownloader.downloadFileToFileSystem(RunnableDownloader.java:185)
	at com.google.api.ads.adwords.awreporting.downloader.RunnableDownloader.run(RunnableDownloader.java:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source ads.properties
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
	at com.google.api.ads.common.lib.conf.ConfigurationHelper.fromFile(ConfigurationHelper.java:61)
	... 37 more

pom.xml:API version

 <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <springframework.version>3.2.2.RELEASE</springframework.version>
    <google-client.version>1.18.0-rc</google-client.version>
    <com.google.api-ads.version>2.15.0</com.google.api-ads.version>
  </properties>

**Comment by chenzhuo914** [comment]
Interesting, the ONMEMORY and ONFILE only differ on report processing, but not configuration loading. This project should not require "ads.properties", which is properties file name for the AdWords API Java client library.

I will try to upgrade to v201605 and see if I can reproduce this issue.

**Comment by GirijaSankar61** [comment]
Thank you for your reply.This issue is resolved.It was showing on a specific system.

**Comment by chenzhuo914** [comment]
Cool, thanks for the info!
