### ISSUE TITLE
Error when using QualityScore in KeywordPerformanceReport

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#254]
Hi!

While running the latest AwReporting version (API v201607) for the first time, we received the following error repeatedly on the KeywordPerformanceReport:

```
Error Parsing column # 1 with contents:  --
Error Parsing PropertyDescriptor: java.beans.PropertyDescriptor[name=qualityScore; propertyType=class java.lang.Long; readMethod=public java.lang.Long com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords.getQualityScore(); writeMethod=public void com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords.setQualityScore(java.lang.Long)]
[15 Sep 2016 12:19:24,393-RunnableProcessorOnFile:ERROR:pool-2-thread-13] Error processing file: /tmp/reportDownload-KEYWORDS_PERFORMANCE_REPORT-9372911668-7168491296421712872.report.gunzip
2016-09-15 12:19:24,393 [ERROR|com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile|RunnableProcessorOnFile] Error processing file: /tmp/reportDownload-KEYWORDS_PERFORMANCE_REPORT-9372911668-7168491296421712872.report.gunzip
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: Zero length string
        at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile.run(RunnableProcessorOnFile.java:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: Zero length string
        at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:125)
        at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:55)
        ... 6 more
Caused by: java.lang.NumberFormatException: Zero length string
        at java.lang.Long.decode(Long.java:630)
        at com.sun.beans.editors.LongEditor.setAsText(LongEditor.java:45)
        at au.com.bytecode.opencsv.bean.CsvToBean.convertValue(CsvToBean.java:82)
        at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:105)
        ... 7 more
```

The properties file part for the report looks like this:

`KEYWORDS_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,ConversionsManyPerClick,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,QualityScore,KeywordMatchType,Criteria,CriteriaDestinationUrl,AdGroupId,CampaignId,Status,IsNegative,Labels`

As the error is in reference to the **QualityScore**, I removed that field from the properties and was able to run the report again without any problems. This might be related to the newly added "--" value for the QS introduced in v201607.

We currently don't use QualityScore, so we can do without it for now, but it would be good if this could be resolved. Thanks!

**Comment by praflo** [comment]
I have the same issue. This error seems to generate from this change: 
http://googleadsdeveloper.blogspot.it/2016/08/changes-to-quality-score-in-adwords.html

As a result, the downloaded file may contain lines like this:

> Keyword ID,Quality score,Ad relevance,Landing page experience
> 1234567890, --,Not applicable,Not applicable,Not applicable

I think that those "--" are generating the error.

How to fix this?

We do use QS and we need it.
A quick patch would be more than welcome.

**Comment by chenzhuo914** [comment]
Hi Tim and Praflo, thanks for reporting this issue! It's indeed due to the change of QualityScore, which returns "--" that cannot be parsed to an integer.

The easy fix is to change "QualityScore" type from Long to String, so it can handle possible NULL values. I've made commit cc843ffdfc7fa7307721a3213ffa959ee6d63883, please pull the latest code.

**Comment by praflo** [comment]
Hello chenzhuo914,
This patch has the side effect that the initial tests (mvn compile...) fail when checking QualityScore as long:
  ```
Tests in error:
testCSVMapping(com.google.api.ads.adwords.awreporting.model.definitions.ReportKeywordsDefinitionTest): com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords.getQualityScore()Ljava/lang/Long;
  testSQLPersistence(com.google.api.ads.adwords.awreporting.model.definitions.ReportKeywordsDefinitionTest): com.google.api.ads.adwords.awreporting.model.entities.ReportKeywords.getQualityScore()Ljava/lang/Long;
```

To temporarily solve this I have disabled the checks on QS (ReportKeywordsDefinitionTest.java lines 68 and100) and compilation completes succesfully.

**Comment by chenzhuo914** [comment]
Sorry I forgot to update tests. I've just committed another fix for test cases, it should solve your problem now.

**Comment by praflo** [comment]
Another error now:

`Caused by: java.sql.BatchUpdateException: Incorrect decimal value: ' --' for column 'QUALITY_SCORE' at row 1`

(full errror below)

Not sure what's the best solution here. Are there still zero QS keywords or these keywords have been converted to "--" ? If zero QS keywords are still there, I would not force "--" as a 0 (zero)  as this could mix up zero QS keywords and "--" keywords. 

Maybe set "--" QS keywords to -1 value? 

Changing QUALITY_SCORE field type from decimal to string may create problems on programs that need numeric values for QS and not strings.


`[19 Sep 2016 10:45:59,395-RunnableProcessorOnMemory:ERROR:pool-2-thread-10] Error processing report for account: 01234567890 JDBC exception on Hibernate data access: SQLException for SQL [insert into AW_ReportKeyword (ACCOUNT_ID, DATE_END, DATE_RANGE_TYPE, DATE_START, PARTNER_ID, TIMESTAMP, TOP_ACCOUNT_ID, ACCOUNT_DESCRIPTIVE_NAME, ACCOUNTTIMEZONEID, NETWORK, NETWORK_PARTNERS, ALL_CONVERSION_RATE, ALL_CONVERSION_VALUE, ALL_CONVERSIONS, AVERAGE_COST, AVERAGE_CPC, AVERAGE_CPE, AVERAGE_CPM, AVERAGE_CPV, AVERAGE_POSITION, CLICK_TYPE, CLICKS, CONVERSIONCATEGORYNAME, CONVERSION_RATE, CONVERSIONTYPENAME, CONVERSION_VALUE, CONVERSIONS, COST, COST_PER_ALL_CONVERSION, COST_PER_CONVERSION, CTR, CURRENCY_CODE, CUSTOMER_DESCRIPTIVE_NAME, DAY, DAYOFWEEK, DEVICE, ENGAGEMENT_RATE, ENGAGEMENTS, IMPRESSIONS, INTERACTION_RATE, INTERACTIONS, MONTH, MONTH_OF_YEAR, PRIMARYCOMPANYNAME, QUARTER, VALUE_PER_ALL_CONVERSION, VALUE_PER_CONVERSION, VIDEO_VIEW_RATE, VIDEO_VIEWS, VIEWTHROUGHCONVERSIONS, WEEK, YEAR, ACTIVE_VIEW_CPM, ACTIVE_VIEW_CTR, ACTIVE_VIEW_IMPRESSIONS, ACTIVE_VIEW_MEASURABILITY, ACTIVE_VIEW_MEASURABLE_COST, ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, ACTIVE_VIEW_VIEWABILITY, ADGROUP_ID, ADGROUP_NAME, AVERAGE_PAGEVIEWS, AVERAGE_TIME_ON_SITE, BOUNCE_RATE, CAMPAIGN_ID, CAMPAIGN_NAME, CONVERSION_TRACKER_ID, CREATIVE_QUALITY_SCORE, CRITERIA, CRITERIA_DESTINATION_URL, ENHANCED_CPC_ENABLED, ESTIMATED_ADD_CLICKS_AT_FIRST_POSITION_CPC, ESTIMATED_ADD_COST_AT_FIRST_POSITION_CPC, FINAL_APP_URLS, FINAL_MOBILE_URLS, FINAL_URLS, FIRST_PAGE_CPC, FIRST_POSITION_CPC, GMAIL_FORWARDS, GMAIL_SAVES, GMAIL_SECONDARY_CLICKS, KEYWORD_ID, KEYWORD_MATCH_TYPE, LABELS, MAX_CPC, MAX_CPM, IS_NEGATIVE, PERCENT_NEW_VISITORS, POST_CLICK_QUALITY_SCORE, QUALITY_SCORE, SEARCH_EXACT_MATCH_IMPRESSION_SHARE, SEARCH_IMPRESSION_SHARE, SEARCH_LOST_IS_RANK, SEARCH_PREDICTED_CTR, SLOT, STATUS, SYSTEM_SERVING_STATUS, TOP_OF_PAGE_CPC, TRACKING_URL_TEMPLATE, URL_CUSTOM_PARAMETERS, VIDEO_QUARTILE_100_RATE, VIDEO_QUARTILE_25_RATE, VIDEO_QUARTILE_50_RATE, VIDEO_QUARTILE_75_RATE, ROW_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; could not perform addBatch; nested exception is org.hibernate.exception.GenericJDBCException: could not perform addBatch
2016-09-19 10:45:59,395 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: 01234567890 JDBC exception on Hibernate data access: SQLException for SQL [insert into AW_ReportKeyword (ACCOUNT_ID, DATE_END, DATE_RANGE_TYPE, DATE_START, PARTNER_ID, TIMESTAMP, TOP_ACCOUNT_ID, ACCOUNT_DESCRIPTIVE_NAME, ACCOUNTTIMEZONEID, NETWORK, NETWORK_PARTNERS, ALL_CONVERSION_RATE, ALL_CONVERSION_VALUE, ALL_CONVERSIONS, AVERAGE_COST, AVERAGE_CPC, AVERAGE_CPE, AVERAGE_CPM, AVERAGE_CPV, AVERAGE_POSITION, CLICK_TYPE, CLICKS, CONVERSIONCATEGORYNAME, CONVERSION_RATE, CONVERSIONTYPENAME, CONVERSION_VALUE, CONVERSIONS, COST, COST_PER_ALL_CONVERSION, COST_PER_CONVERSION, CTR, CURRENCY_CODE, CUSTOMER_DESCRIPTIVE_NAME, DAY, DAYOFWEEK, DEVICE, ENGAGEMENT_RATE, ENGAGEMENTS, IMPRESSIONS, INTERACTION_RATE, INTERACTIONS, MONTH, MONTH_OF_YEAR, PRIMARYCOMPANYNAME, QUARTER, VALUE_PER_ALL_CONVERSION, VALUE_PER_CONVERSION, VIDEO_VIEW_RATE, VIDEO_VIEWS, VIEWTHROUGHCONVERSIONS, WEEK, YEAR, ACTIVE_VIEW_CPM, ACTIVE_VIEW_CTR, ACTIVE_VIEW_IMPRESSIONS, ACTIVE_VIEW_MEASURABILITY, ACTIVE_VIEW_MEASURABLE_COST, ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, ACTIVE_VIEW_VIEWABILITY, ADGROUP_ID, ADGROUP_NAME, AVERAGE_PAGEVIEWS, AVERAGE_TIME_ON_SITE, BOUNCE_RATE, CAMPAIGN_ID, CAMPAIGN_NAME, CONVERSION_TRACKER_ID, CREATIVE_QUALITY_SCORE, CRITERIA, CRITERIA_DESTINATION_URL, ENHANCED_CPC_ENABLED, ESTIMATED_ADD_CLICKS_AT_FIRST_POSITION_CPC, ESTIMATED_ADD_COST_AT_FIRST_POSITION_CPC, FINAL_APP_URLS, FINAL_MOBILE_URLS, FINAL_URLS, FIRST_PAGE_CPC, FIRST_POSITION_CPC, GMAIL_FORWARDS, GMAIL_SAVES, GMAIL_SECONDARY_CLICKS, KEYWORD_ID, KEYWORD_MATCH_TYPE, LABELS, MAX_CPC, MAX_CPM, IS_NEGATIVE, PERCENT_NEW_VISITORS, POST_CLICK_QUALITY_SCORE, QUALITY_SCORE, SEARCH_EXACT_MATCH_IMPRESSION_SHARE, SEARCH_IMPRESSION_SHARE, SEARCH_LOST_IS_RANK, SEARCH_PREDICTED_CTR, SLOT, STATUS, SYSTEM_SERVING_STATUS, TOP_OF_PAGE_CPC, TRACKING_URL_TEMPLATE, URL_CUSTOM_PARAMETERS, VIDEO_QUARTILE_100_RATE, VIDEO_QUARTILE_25_RATE, VIDEO_QUARTILE_50_RATE, VIDEO_QUARTILE_75_RATE, ROW_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; could not perform addBatch; nested exception is org.hibernate.exception.GenericJDBCException: could not perform addBatch
org.springframework.orm.hibernate4.HibernateJdbcException: JDBC exception on Hibernate data access: SQLException for SQL [insert into AW_ReportKeyword (ACCOUNT_ID, DATE_END, DATE_RANGE_TYPE, DATE_START, PARTNER_ID, TIMESTAMP, TOP_ACCOUNT_ID, ACCOUNT_DESCRIPTIVE_NAME, ACCOUNTTIMEZONEID, NETWORK, NETWORK_PARTNERS, ALL_CONVERSION_RATE, ALL_CONVERSION_VALUE, ALL_CONVERSIONS, AVERAGE_COST, AVERAGE_CPC, AVERAGE_CPE, AVERAGE_CPM, AVERAGE_CPV, AVERAGE_POSITION, CLICK_TYPE, CLICKS, CONVERSIONCATEGORYNAME, CONVERSION_RATE, CONVERSIONTYPENAME, CONVERSION_VALUE, CONVERSIONS, COST, COST_PER_ALL_CONVERSION, COST_PER_CONVERSION, CTR, CURRENCY_CODE, CUSTOMER_DESCRIPTIVE_NAME, DAY, DAYOFWEEK, DEVICE, ENGAGEMENT_RATE, ENGAGEMENTS, IMPRESSIONS, INTERACTION_RATE, INTERACTIONS, MONTH, MONTH_OF_YEAR, PRIMARYCOMPANYNAME, QUARTER, VALUE_PER_ALL_CONVERSION, VALUE_PER_CONVERSION, VIDEO_VIEW_RATE, VIDEO_VIEWS, VIEWTHROUGHCONVERSIONS, WEEK, YEAR, ACTIVE_VIEW_CPM, ACTIVE_VIEW_CTR, ACTIVE_VIEW_IMPRESSIONS, ACTIVE_VIEW_MEASURABILITY, ACTIVE_VIEW_MEASURABLE_COST, ACTIVE_VIEW_MEASURABLE_IMPRESSIONS, ACTIVE_VIEW_VIEWABILITY, ADGROUP_ID, ADGROUP_NAME, AVERAGE_PAGEVIEWS, AVERAGE_TIME_ON_SITE, BOUNCE_RATE, CAMPAIGN_ID, CAMPAIGN_NAME, CONVERSION_TRACKER_ID, CREATIVE_QUALITY_SCORE, CRITERIA, CRITERIA_DESTINATION_URL, ENHANCED_CPC_ENABLED, ESTIMATED_ADD_CLICKS_AT_FIRST_POSITION_CPC, ESTIMATED_ADD_COST_AT_FIRST_POSITION_CPC, FINAL_APP_URLS, FINAL_MOBILE_URLS, FINAL_URLS, FIRST_PAGE_CPC, FIRST_POSITION_CPC, GMAIL_FORWARDS, GMAIL_SAVES, GMAIL_SECONDARY_CLICKS, KEYWORD_ID, KEYWORD_MATCH_TYPE, LABELS, MAX_CPC, MAX_CPM, IS_NEGATIVE, PERCENT_NEW_VISITORS, POST_CLICK_QUALITY_SCORE, QUALITY_SCORE, SEARCH_EXACT_MATCH_IMPRESSION_SHARE, SEARCH_IMPRESSION_SHARE, SEARCH_LOST_IS_RANK, SEARCH_PREDICTED_CTR, SLOT, STATUS, SYSTEM_SERVING_STATUS, TOP_OF_PAGE_CPC, TRACKING_URL_TEMPLATE, URL_CUSTOM_PARAMETERS, VIDEO_QUARTILE_100_RATE, VIDEO_QUARTILE_25_RATE, VIDEO_QUARTILE_50_RATE, VIDEO_QUARTILE_75_RATE, ROW_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; could not perform addBatch; nested exception is org.hibernate.exception.GenericJDBCException: could not perform addBatch
        at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:146)
        at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:680)
        at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:562)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:270)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy21.persistReportEntities(Unknown Source)
        at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:153)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: org.hibernate.exception.GenericJDBCException: could not perform addBatch
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:54)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:114)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:101)
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:149)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:198)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:359)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:277)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:328)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:52)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1234)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:404)
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:175)
        at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:554)
        ... 12 more
Caused by: java.sql.BatchUpdateException: Incorrect decimal value: ' --' for column 'QUALITY_SCORE' at row 1
        at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1469)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1071)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:110)`

**Comment by chenzhuo914** [comment]
That's because your database table still has QUALITY_SCORE column as int type, not String.

Anyway I made a better fix - keep QualityScore as int, but do some sanity cleanup when the report returns null value, and use "0" for number types in that case. I've checked in the fix, please try again.
