### ISSUE TITLE
Cannot process Kratus after upgrade

### ISSUE THREAD

**Issue by Jaccib3006** [googleads/aw-reporting#261]
Hi, receiving the following message when trying to process the daily Kratus. Could anyone help me with this error, the daily download is working without any issues.  Thanks  Jacci
 ** Generating Kratus (for: 3812) **
index: { "v" : 1 , "key" : { "_id" : 1} , "name" : "_id_" , "ns" : "AdWordsReports.com.google.api.ads.adwords.awreporting.server.ent
index: { "v" : 1 , "key" : { "externalCustomerId" : 1 , "day" : 1} , "name" : "externalCustomerId_1_day_1" , "ns" : "AdWordsReports.s.awreporting.server.entities.Kratu"}
index: { "v" : 1 , "key" : { "day" : 1} , "name" : "day_1" , "ns" : "AdWordsReports.com.google.api.ads.adwords.awreporting.server.en

0java.lang.NullPointerException
        at java.math.BigDecimal.add(BigDecimal.java:1083)
        at com.google.api.ads.adwords.awreporting.server.entities.Kratu.addConversions(Kratu.java:688)
        at com.google.api.ads.adwords.awreporting.server.kratu.KratuCompute.createDailyKratuFromDB(KratuCompute.java:204)
        at com.google.api.ads.adwords.awreporting.server.kratu.RunnableKratu.run(RunnableKratu.java:85)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by chenzhuo914** [comment]
Here there, I don't have your running configurations, but looking at the call stack it seems the "Conversion" value is null, leading to the NullPointerException.

I checked and it turns out that the properties file is still using "ConvertedClicks" instead of "Conversions", which is the possible culprit. I updated it in commit 37a13590c591e84ea265e9f9ef87d39c9ba78c60, please apply the change and try again.

**Comment by chenzhuo914** [comment]
Closing since there's no reply for 2 months. Also, we will be removing the server modules in v2 release, please refer to [this blog post](http://googleadsdeveloper.blogspot.com/2017/01/upcoming-changes-to-awreporting.html) for details and feedback.
