### ISSUE TITLE
RuntimeException: java.net.SocketException

### ISSUE THREAD

**Issue by juneswang2016** [googleads/aw-reporting#264]
Hi

When running the application, Response received with status code is OK, but i sometimes get the following error:

[12 一月 2017 12:34:05,138-RunnableProcessorOnMemory:ERROR:pool-2-thread-1] Error processing report for account: XXXXXXXXX java.net.SocketException: Connection reset
2017-01-12 12:34:05,138 [ERROR|com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory|RunnableProcessorOnMemory] Error processing report for account: XXXXXXXXX java.net.SocketException: Connection reset
java.lang.RuntimeException: java.net.SocketException: Connection reset
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.api.ads.adwords.awreporting.processors.onmemory.RunnableProcessorOnMemory.run(RunnableProcessorOnMemory.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:554)
        at sun.security.ssl.InputRecord.read(InputRecord.java:509)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3066)
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.readLine(BufferedReader.java:317)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at au.com.bytecode.opencsv.CSVReader.getNextLine(CSVReader.java:266)
	at au.com.bytecode.opencsv.CSVReader.readNext(CSVReader.java:233)
        at com.google.api.ads.adwords.awreporting.model.csv.AwReportCsvReader.readNext(AwReportCsvReader.java:167)
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:53)

-------------------------------------------------------------------------------------------------------------------
The Error while  run the Geo Report using Report Processor Type ONMEMORY. Works fine when using ONFILE. 
It completed without any issues,if reducing selected segment fields.(Type=ONMEMORY)

**Comment by chenzhuo914** [comment]
I'm not quite sure what's happening, by javadoc SocketException indicates there's error in the underlying protocol. Could you try some debug tool such as Wireshark to view the actual network packets?

**Comment by juneswang2016** [comment]
Thanks for returning me. This seems to be memory problems, I try to another PC, no problem, it‘s work.
Thanks again.
