### ISSUE TITLE
Can't get rid of ""org.hibernate.NonUniqueObjectException:" for Placement Performance Report

### ISSUE THREAD

**Issue by GarikTate** [googleads/aw-reporting#280]
I keep getting the following error when I try to run my Placement Performance Report.
` ** Generating: PLACEMENT_PERFORMANCE_REPORT **
[06 Oct 2017 08:01:17,034-StreamingReportProcessor:INFO:main]  Processing reports...
[06 Oct 2017 08:01:17,035-StreamingReportProcessor:INFO:main] Processing report streams...
[06 Oct 2017 08:01:18,647-StreamingRunnableProcessor:ERROR:pool-1-thread-1] Runtime error processing report for account: 3307331286
org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [com.google.api.ads.adwords.awreporting.model.entities.PlacementPerformanceReport#3307331286-2017-08-01]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:179)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:135)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:206)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:191)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
        at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
        at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:735)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:727)
        at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:723)
        at com.google.api.ads.adwords.awreporting.model.persistence.sql.SqlReportEntitiesPersister.persistReportEntities(SqlReportEntitiesPersister.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy17.persistReportEntities(Unknown Source)
        at com.google.api.ads.adwords.awreporting.processors.stream.StreamingRunnableProcessor.parseCsv(StreamingRunnableProcessor.java:193)
        at com.google.api.ads.adwords.awreporting.processors.stream.StreamingRunnableProcessor.run(StreamingRunnableProcessor.java:118)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[06 Oct 2017 08:01:18,654-StreamingReportProcessor:INFO:main] *** Finished processing all reports in 1 seconds ***
`

I've tried every configuration I can think of.
Including:
`PLACEMENT_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Criteria,Cost`

And when I got desperate and attempted to download everything:
`PLACEMENT_PERFORMANCE_REPORT=ExternalCustomerId,Date,DayOfWeek,Month,MonthOfYear,Quarter,Week,Year,AccountCurrencyCode,AccountDescriptiveName,AccountTimeZone,ActiveViewCpm,ActiveViewCtr,ActiveViewImpressions,ActiveViewMeasurability,ActiveViewMeasurableCost,ActiveViewMeasurableImpressions,ActiveViewViewability,AdGroupId,AdGroupName,AdGroupStatus,AdNetworkType1,AdNetworkType2,AllConversionRate,AllConversionValue,AllConversions,AverageCost,AverageCpc,AverageCpe,AverageCpm,AverageCpv,BaseAdGroupId,BaseCampaignId,BidModifier,BidType,CampaignId,CampaignName,CampaignStatus,Clicks,ConversionRate,ConversionValue,Conversions,Cost,CostPerAllConversion,CostPerConversion,CpcBid,CpcBidSource,CpmBid,CpmBidSource,Criteria,CriteriaDestinationUrl,CrossDeviceConversions,Ctr,CustomerDescriptiveName,Device,DisplayName,EngagementRate,Engagements,FinalAppUrls,FinalMobileUrls,FinalUrls,GmailForwards,GmailSaves,GmailSecondaryClicks,Id,Impressions,InteractionRate,InteractionTypes,Interactions,IsNegative,IsRestrict,Status,TrackingUrlTemplate,UrlCustomParameters,ValuePerAllConversion,ValuePerConversion,VideoQuartile100Rate,VideoQuartile25Rate,VideoQuartile50Rate,VideoQuartile75Rate,VideoViewRate,VideoViews,ViewThroughConversions`

I've only found this error when trying to download Placement Performance Report, and nothing else.

**Comment by nwbirnie** [comment]
This looks like an issue with the ID generation for segmented reports. Specifically, PlacementPerformanceReport may return multiple rows when segmented (e.g. by date) but it looks like the persistence layer isn't handling this. I'll investigate a fix and get back to you.

**Comment by nwbirnie** [comment]
So fixing this issue will require a change to the primary key structure in the database schema. This will take a bit of time to get right, and we'll need to be very careful with existing data. In the meantime, if anyone is blocked from getting started due to this issue, please reach out and I'll be happy to provide guidance on a manual migration.

**Comment by nwbirnie** [comment]
The latest release includes an error message when this occurs. The fix is to include missing fields, which are provided in the message. Closing this out.
