### ISSUE TITLE
 Error creating bean with name 'sqlReportEntitiesPersister'

### ISSUE THREAD

**Issue by ErmalKristo** [googleads/aw-reporting#281]
Hello

Just finished installing the latest version of aw-reporting. 
I'm getting this error:
_$ java -Xmx1G -jar aw-reporting/target/aw-reporting.jar -startDate $(date --date="1 days ago" +%Y%m%d) -endDate $(date --date="1 days ago" +%Y%m%d)  -file aw-reporting/src/main/resources/aw-report-sample.properties_

**[11 Oct 2017 12:08:22,273-AwReporting:INFO:main] Using properties file: aw-reporting/src/main/resources/aw-report-sample.properties
[11 Oct 2017 12:08:22,437-AwReporting:INFO:main] Using MYSQL DB configuration properties.
[11 Oct 2017 12:08:22,437-AwReporting:INFO:main] Using MEMORY Processor.
[11 Oct 2017 12:08:22,501-AwReporting:WARN:main] Updating database schema, this could take a few minutes ...
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlReportEntitiesPersister' defined in URL [jar:file:/root/awreporting/aw-reporting/aw-reporting/target/dependency/aw-reporting-model-2.2.0.jar!/com/google/api/ads/adwords/awreporting/model/persistence/sql/SqlReportEntitiesPersister.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.hibernate.SessionFactory]: : Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:730)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:196)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1051)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:955)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:490)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at com.google.api.ads.adwords.awreporting.AwReporting.init(AwReporting.java:369)
        at com.google.api.ads.adwords.awreporting.AwReporting.main(AwReporting.java:132)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1488)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:910)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:853)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:768)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:795)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: javax/transaction/SystemException
        at java.lang.Class.forName0(java.base@9-internal/Native Method)
        at java.lang.Class.forName(java.base@9-internal/Class.java:378)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2248)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2214)
        at org.hibernate.cfg.Configuration.<clinit>(Configuration.java:179)
        at org.springframework.orm.hibernate4.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:278)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1485)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: javax.transaction.SystemException
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
        at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
        ... 33 more**

Thanks in advance

**Comment by nwbirnie** [comment]
Looks like a missing dependency for JTA. Could you run `mvn dependency:tree -f aw-reporting/pom.xml` and post the output here please.

**Comment by ErmalKristo** [comment]
Hello Nick

Thank you for your prompt response.

Here the output of the command:

**[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building aw-reporting 2.2.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ aw-reporting ---
[INFO] com.google.api-ads:aw-reporting:jar:2.2.0
[INFO] +- com.google.api-ads:aw-reporting-model:jar:2.2.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:3.2.2.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:3.2.2.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:3.2.2.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-orm:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.springframework:spring-jdbc:jar:3.2.2.RELEASE:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:4.2.1.Final:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.1.0.GA:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.1.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.15.0-GA:compile
[INFO] |  |  \- org.hibernate.common:hibernate-commons-annotations:jar:4.0.1.Final:compile
[INFO] |  +- org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile
[INFO] |  +- com.opencsv:opencsv:jar:3.8:compile
[INFO] |  +- org.apache.commons:commons-csv:jar:1.2:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- org.mongodb:mongo-java-driver:jar:2.11.0:compile
[INFO] |  \- javax.jdo:jdo2-api:jar:2.3-eb:compile
[INFO] |     \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] +- com.google.api-ads:ads-lib:jar:3.7.0:compile
[INFO] |  +- com.google.inject:guice:jar:4.0:compile
[INFO] |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- com.google.inject.extensions:guice-assistedinject:jar:4.0:compile
[INFO] |  +- com.google.inject.extensions:guice-multibindings:jar:4.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  +- commons-configuration:commons-configuration:jar:1.10:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:1.8:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |  |  \- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  |     \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |     \- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  \- com.beust:jcommander:jar:1.48:compile
[INFO] +- com.google.api-ads:adwords-appengine:jar:3.7.0:compile
[INFO] |  \- com.google.api-ads:ads-lib-appengine:jar:3.7.0:compile
[INFO] |     \- com.google.api-client:google-api-client-appengine:jar:1.22.0:compile
[INFO] |        +- com.google.oauth-client:google-oauth-client-appengine:jar:1.22.0:compile
[INFO] |        |  +- com.google.oauth-client:google-oauth-client-servlet:jar:1.22.0:compile
[INFO] |        |  |  \- com.google.http-client:google-http-client-jdo:jar:1.22.0:compile
[INFO] |        |  \- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |        +- com.google.api-client:google-api-client-servlet:jar:1.22.0:compile
[INFO] |        \- com.google.http-client:google-http-client-appengine:jar:1.22.0:compile
[INFO] +- com.google.api-ads:adwords-extension-ratelimiter:jar:0.1.0:compile
[INFO] +- joda-time:joda-time:jar:2.2:compile
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.7:compile
[INFO] +- com.samskivert:jmustache:jar:1.8:compile
[INFO] +- org.xhtmlrenderer:core-renderer:jar:R8:compile
[INFO] +- com.lowagie:itext:jar:2.0.8:compile
[INFO] |  +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |  \- bouncycastle:bcprov-jdk14:jar:138:compile
[INFO] +- commons-cli:commons-cli:jar:1.3:compile
[INFO] +- commons-io:commons-io:jar:1.3.2:compile
[INFO] +- com.google.guava:guava:jar:20.0:compile
[INFO] +- junit:junit:jar:4.10:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.1:test
[INFO] +- org.mockito:mockito-all:jar:1.8.5:test
[INFO] +- mysql:mysql-connector-java:jar:5.1.6:compile
[INFO] +- net.sourceforge.jtds:jtds:jar:1.3.0:compile
[INFO] \- com.google.apis:google-api-services-drive:jar:v2-rev113-1.17.0-rc:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.384 s
[INFO] Finished at: 2017-10-11T12:48:37+02:00
[INFO] Final Memory: 15M/219M
[INFO] ------------------------------------------------------------------------**

**Comment by nwbirnie** [comment]
That looks good, the JTA dependency is being resolved. So Java isn't seeing the dependencies at runtime. These are copied to aw-reporting/target/lib, so can you try changing to the target directory before running? E.g.
```
cd aw-reporting/target
java -Xmx1G -jar aw-reporting.jar 
```

**Comment by ErmalKristo** [comment]
Same output even after changing directory to aw-reporting/target

_$ java -Xmx1G -jar aw-reporting.jar -startDate $(date --date="1 days ago" +%Y%m%d) -endDate $(date --date="1 days ago" +%Y%m%d)  -file ~/awreporting/aw-reporting/aw-reporting/src/main/resources/aw-report-sample.properties_

**[11 Oct 2017 13:06:44,007-AwReporting:INFO:main] Using properties file: /root/awreporting/aw-reporting/aw-reporting/src/main/resources/aw-report-sample.properties
[11 Oct 2017 13:06:44,163-AwReporting:INFO:main] Using MYSQL DB configuration properties.
[11 Oct 2017 13:06:44,163-AwReporting:INFO:main] Using MEMORY Processor.
[11 Oct 2017 13:06:44,288-AwReporting:WARN:main] Updating database schema, this could take a few minutes ...
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlReportEntitiesPersister' defined in URL [jar:file:/root/awreporting/aw-reporting/aw-reporting/target/dependency/aw-reporting-model-2.2.0.jar!/com/google/api/ads/adwords/awreporting/model/persistence/sql/SqlReportEntitiesPersister.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.hibernate.SessionFactory]: : Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException**

**Comment by nwbirnie** [comment]
Can you paste the output of:

- `java -version`
- `ls lib`

**Comment by ErmalKristo** [comment]
_root@ubuntu:~/awreporting/aw-reporting/aw-reporting/target# java -version_
**openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)**



_root@ubuntu:~/awreporting/aw-reporting/aw-reporting/target# ll lib_
total 31340
**drwxr-xr-x  2 root root    4096 Oct 11 11:23 ./
drwxr-xr-x 11 root root    4096 Oct 11 13:06 ../
-rw-r--r--  1 root root  558157 Oct 11 11:23 ads-lib-3.7.0.jar
-rw-r--r--  1 root root   13306 Oct 11 11:23 ads-lib-appengine-3.7.0.jar
-rw-r--r--  1 root root 4561462 Oct 11 11:23 adwords-appengine-3.7.0.jar
-rw-r--r--  1 root root   26616 Oct 11 11:23 adwords-extension-ratelimiter-0.1.0.jar
-rw-r--r--  1 root root  445288 Oct 11 11:23 antlr-2.7.7.jar
-rw-r--r--  1 root root    4467 Oct 11 11:23 aopalliance-1.0.jar
-rw-r--r--  1 root root  339481 Oct 11 11:23 aw-reporting-model-2.2.0.jar
-rw-r--r--  1 root root  192035 Oct 11 11:23 bcmail-jdk14-138.jar
-rw-r--r--  1 root root 1551468 Oct 11 11:23 bcprov-jdk14-138.jar
-rw-r--r--  1 root root  233859 Oct 11 11:23 commons-beanutils-1.9.2.jar
-rw-r--r--  1 root root   52946 Oct 11 11:23 commons-cli-1.3.jar
-rw-r--r--  1 root root  284184 Oct 11 11:23 commons-codec-1.10.jar
-rw-r--r--  1 root root  588337 Oct 11 11:23 commons-collections-3.2.2.jar
-rw-r--r--  1 root root  362679 Oct 11 11:23 commons-configuration-1.10.jar
-rw-r--r--  1 root root   38795 Oct 11 11:23 commons-csv-1.2.jar
-rw-r--r--  1 root root   87776 Oct 11 11:23 commons-io-1.3.2.jar
-rw-r--r--  1 root root  284220 Oct 11 11:23 commons-lang-2.6.jar
-rw-r--r--  1 root root  434678 Oct 11 11:23 commons-lang3-3.4.jar
-rw-r--r--  1 root root   60686 Oct 11 11:23 commons-logging-1.1.1.jar
-rw-r--r--  1 root root 1079323 Oct 11 11:23 core-renderer-R8.jar
-rw-r--r--  1 root root  313898 Oct 11 11:23 dom4j-1.6.1.jar
-rw-r--r--  1 root root  199100 Oct 11 11:23 google-api-client-1.22.0.jar
-rw-r--r--  1 root root    9868 Oct 11 11:23 google-api-client-appengine-1.22.0.jar
-rw-r--r--  1 root root    6553 Oct 11 11:23 google-api-client-servlet-1.22.0.jar
-rw-r--r--  1 root root  151323 Oct 11 11:23 google-api-services-drive-v2-rev113-1.17.0-rc.jar
-rw-r--r--  1 root root  357024 Oct 11 11:23 google-http-client-1.22.0.jar
-rw-r--r--  1 root root   15670 Oct 11 11:23 google-http-client-appengine-1.22.0.jar
-rw-r--r--  1 root root    6720 Oct 11 11:23 google-http-client-jackson2-1.22.0.jar
-rw-r--r--  1 root root   11273 Oct 11 11:23 google-http-client-jdo-1.22.0.jar
-rw-r--r--  1 root root   61342 Oct 11 11:23 google-oauth-client-1.22.0.jar
-rw-r--r--  1 root root    7944 Oct 11 11:23 google-oauth-client-appengine-1.22.0.jar
-rw-r--r--  1 root root   22025 Oct 11 11:23 google-oauth-client-servlet-1.22.0.jar
-rw-r--r--  1 root root  190432 Oct 11 11:23 gson-2.2.4.jar
-rw-r--r--  1 root root 2442625 Oct 11 11:23 guava-20.0.jar
-rw-r--r--  1 root root  668235 Oct 11 11:23 guice-4.0.jar
-rw-r--r--  1 root root   43425 Oct 11 11:23 guice-assistedinject-4.0.jar
-rw-r--r--  1 root root   81388 Oct 11 11:23 guice-multibindings-4.0.jar
-rw-r--r--  1 root root   76643 Oct 11 11:23 hamcrest-core-1.1.jar
-rw-r--r--  1 root root   81271 Oct 11 11:23 hibernate-commons-annotations-4.0.1.Final.jar
-rw-r--r--  1 root root 4613189 Oct 11 11:23 hibernate-core-4.2.1.Final.jar
-rw-r--r--  1 root root  102661 Oct 11 11:23 hibernate-jpa-2.0-api-1.0.1.Final.jar
-rw-r--r--  1 root root  291037 Oct 11 11:23 httpclient-4.0.1.jar
-rw-r--r--  1 root root  172888 Oct 11 11:23 httpcore-4.0.1.jar
-rw-r--r--  1 root root 1213150 Oct 11 11:23 itext-2.0.8.jar
-rw-r--r--  1 root root  206797 Oct 11 11:23 jackson-core-2.1.3.jar
-rw-r--r--  1 root root  648253 Oct 11 11:23 javassist-3.15.0-GA.jar
-rw-r--r--  1 root root    2497 Oct 11 11:23 javax.inject-1.jar
-rw-r--r--  1 root root   60768 Oct 11 11:23 jboss-logging-3.1.0.GA.jar
-rw-r--r--  1 root root   25215 Oct 11 11:23 jboss-transaction-api_1.1_spec-1.0.1.Final.jar
-rw-r--r--  1 root root   63504 Oct 11 11:23 jcommander-1.48.jar
-rw-r--r--  1 root root  192696 Oct 11 11:23 jdo2-api-2.3-eb.jar
-rw-r--r--  1 root root   54434 Oct 11 11:23 jmustache-1.8.jar
-rw-r--r--  1 root root  573912 Oct 11 11:23 joda-time-2.2.jar
-rw-r--r--  1 root root   33015 Oct 11 11:23 jsr305-1.3.9.jar
-rw-r--r--  1 root root  316066 Oct 11 11:23 jtds-1.3.0.jar
-rw-r--r--  1 root root  253160 Oct 11 11:23 junit-4.10.jar
-rw-r--r--  1 root root  489884 Oct 11 11:23 log4j-1.2.17.jar
-rw-r--r--  1 root root 1419869 Oct 11 11:23 mockito-all-1.8.5.jar
-rw-r--r--  1 root root  417192 Oct 11 11:23 mongo-java-driver-2.11.0.jar
-rw-r--r--  1 root root  703265 Oct 11 11:23 mysql-connector-java-5.1.6.jar
-rw-r--r--  1 root root    8717 Oct 11 11:23 opencsv-1.8.jar
-rw-r--r--  1 root root   64417 Oct 11 11:23 opencsv-3.8.jar
-rw-r--r--  1 root root  105112 Oct 11 11:23 servlet-api-2.5.jar
-rw-r--r--  1 root root   29257 Oct 11 11:23 slf4j-api-1.7.7.jar
-rw-r--r--  1 root root    8870 Oct 11 11:23 slf4j-log4j12-1.7.7.jar
-rw-r--r--  1 root root  335362 Oct 11 11:23 spring-aop-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  607448 Oct 11 11:23 spring-beans-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  861905 Oct 11 11:23 spring-context-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  866788 Oct 11 11:23 spring-core-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  195456 Oct 11 11:23 spring-expression-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  405074 Oct 11 11:23 spring-jdbc-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  387126 Oct 11 11:23 spring-orm-3.2.2.RELEASE.jar
-rw-r--r--  1 root root  242174 Oct 11 11:23 spring-tx-3.2.2.RELEASE.jar
-rw-r--r--  1 root root   15071 Oct 11 11:23 transaction-api-1.1.jar**

**Comment by nwbirnie** [comment]
Ok so looks like an issue with manifest generation. I'll verify this internally and provide a fix shortly. If you like, you could you run `git checkout bug281` and run `mvn clean package` which I think will get you up and running.

**Comment by ErmalKristo** [comment]
Maybe i'm doing something wrong. It doesn't want to work.

_#git checkout remotes/origin/bug281
#root@ubuntu:~/awreporting/aw-reporting# git branch -v -a
* (HEAD detached at origin/bug281)           2bb35c1 fix path to dependencies in manifest
  master                                     c76a864 Migrate to awapi v201708
  remotes/origin/HEAD                        -> origin/master
  remotes/origin/aw-reporting-id             5f4adaa Remove adding date segments to id.
  remotes/origin/aw-reporting-server-dev     cf77d8c Fix for issue #125.
  remotes/origin/aw-reporting-server-pdf-gen ebc25e5 Merge branch 'master' of https://github.com/googleads/aw-reporting
  remotes/origin/bug281                      2bb35c1 fix path to dependencies in manifest
  remotes/origin/churn-prediction            3ee4e7e Merging with master
  remotes/origin/downloadonly                c7c4375 Removing all the unecessary dependencies to the project
  remotes/origin/master                      c76a864 Migrate to awapi v201708
  remotes/origin/misc-cleanup                28e9058 Merge branch 'master' into misc-cleanup
  remotes/origin/v1.13                       cf97bc6 Add a heading notice on readme.
  remotes/origin/zhuoc-dev                   a247e98 Migrate to AdWords API v201609
#mvn clean package
#mvn compile dependency:copy-dependencies package

$ java -Xmx1G -jar aw-reporting.jar -startDate $(date --date="1 days ago" +%Y%m%d) -endDate $(date --date="1 days ago" +%Y%m%d) -file ~/awreporting/aw-reporting/aw-reporting/src/main/resources/aw-report-sample.properties_

**[11 Oct 2017 16:26:00,711-AwReporting:INFO:main] Using properties file: aw-reporting/src/main/resources/aw-report-sample.properties
[11 Oct 2017 16:26:01,310-AwReporting:INFO:main] Using MYSQL DB configuration properties.
[11 Oct 2017 16:26:01,356-AwReporting:INFO:main] Using MEMORY Processor.
[11 Oct 2017 16:26:01,532-AwReporting:WARN:main] Updating database schema, this could take a few minutes ...
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlReportEntitiesPersister' defined in URL [jar:file:/root/awreporting/aw-reporting/aw-reporting/target/lib/aw-reporting-model-2.2.0.jar!/com/google/api/ads/adwords/awreporting/model/persistence/sql/SqlReportEntitiesPersister.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.hibernate.SessionFactory]: : Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException**

**Comment by nwbirnie** [comment]
Hmm, sorry for the back and forth. Could you zip the entire repository directory and upload please?

**Comment by nwbirnie** [comment]
Actually looks like this command `mvn compile dependency:copy-dependencies package` is ignoring the pom classpath prefix for dependencies. Can you just run `mvn clean package` at the repo root and try again please?

**Comment by ErmalKristo** [comment]
#mvn clean package
#$ java -Xmx1G -jar aw-reporting.jar -startDate $(date --date="1 days ago" +%Y%m%d) -endDate $(date --date="1 days ago" +%Y%m%d) -file ~/awreporting/aw-reporting/aw-reporting/src/main/resources/aw-report-sample.properties

[11 Oct 2017 16:46:33,022-AwReporting:INFO:main] Using properties file: aw-reporting/src/main/resources/aw-report-sample.properties
[11 Oct 2017 16:46:33,239-AwReporting:INFO:main] Using MYSQL DB configuration properties.
[11 Oct 2017 16:46:33,240-AwReporting:INFO:main] Using MEMORY Processor.
[11 Oct 2017 16:46:33,311-AwReporting:WARN:main] Updating database schema, this could take a few minutes ...
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlReportEntitiesPersister' defined in URL [jar:file:/root/awreporting/aw-reporting/aw-reporting/target/lib/aw-reporting-model-2.2.0.jar!/com/google/api/ads/adwords/awreporting/model/persistence/sql/SqlReportEntitiesPersister.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.hibernate.SessionFactory]: : Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in class path resource [data-source-mysql.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/transaction/SystemException

Also cannot upload the zip file. It is 33 MB.

**Comment by nwbirnie** [comment]
Could you upload the zip to Google Drive and PM me the sharing link please?

**Comment by ErmalKristo** [comment]
Sent the link via email.

**Comment by ErmalKristo** [comment]
It did the Job.

Thank You Nick
