### ISSUE TITLE
MySQL error for AdPerformanceReport with 2.5.0

### ISSUE THREAD

**Issue by Timmeh74** [googleads/aw-reporting#292]
Hello!

I have recently switched from AwReporting 2.3.0 to 2.5.0 for API v201806 and done the first run yesterday to update the database structure. When downloading data for the AdPerformanceReport, I now get an MySQL error due to a missing field:

```
Runtime error processing report for account: xxxx
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)
[...]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'adperforma_.MultiAssetResponsiveDisplayAdSquareMarketingImages' in 'field list'
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[...]
```

The field _MultiAssetResponsiveDisplayAdSquareMarketingImages_ is not available in the table _AW_AdPerformanceReport_ . No Ad data is stored in the database, but all other reports are running fine (Keyword,Campaign.Adgroup,Account).

My report definition looks like this:

```
AD_PERFORMANCE_REPORT=ExternalCustomerId,Date,AccountDescriptiveName,Cost,Clicks,Impressions,Conversions,Ctr,AverageCpm,AverageCpc,AveragePosition,AccountCurrencyCode,Id,DisplayUrl,Url,Headline,Description1,Description2,AdGroupId,CampaignId,Status,CreativeApprovalStatus,Labels,AdType,HeadlinePart1,HeadlinePart2,Description,Path1,Path2,CreativeFinalUrls,CreativeFinalMobileUrls,CreativeFinalAppUrls,CreativeDestinationUrl
```

Is it ok to add the missing field to the table manually or will that conflict with AwReporting?

**Comment by nwbirnie** [comment]
That is strange, sure you can just create the missing columns. I've attached the [full DDL](https://github.com/googleads/aw-reporting/files/2192405/aw_adperformancereport.txt) for the table which you can use to patch in the missing fields using [alter table](url) statements.

It would be great if you could grab the DDL for your database please so I can investigate the root cause. Either `describe table AW_AdPerformanceReport` or `show create table AW_AdPerformanceReport` would be really helpful.

AW Reporting should push the schema each time it runs, so it's a bit strange that these fields didn't get pushed. Which version of MySQL are you using?

**Comment by Timmeh74** [comment]
Hi!

Actually, your DDL does not contain the field _MultiAssetResponsiveDisplayAdSquareMarketingImages_ either, as far as I can tell.

I'm using MySQL 5.5.60 and here's my current table structure:

```
CREATE TABLE `AW_AdPerformanceReport` (
  `ROW_ID` varchar(255) NOT NULL,
  `ExternalCustomerId` bigint(20) DEFAULT NULL,
  `DATE_RANGE_TYPE` varchar(255) DEFAULT NULL,
  `END_DATE` varchar(255) DEFAULT NULL,
  `START_DATE` varchar(255) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  `TOP_CUSTOMER_ID` bigint(20) DEFAULT NULL,
  `Date` varchar(255) DEFAULT NULL,
  `DayOfWeek` varchar(255) DEFAULT NULL,
  `HourOfDay` bigint(20) DEFAULT NULL,
  `Month` varchar(255) DEFAULT NULL,
  `MonthOfYear` varchar(255) DEFAULT NULL,
  `Quarter` varchar(255) DEFAULT NULL,
  `Week` varchar(255) DEFAULT NULL,
  `Year` bigint(20) DEFAULT NULL,
  `AccountCurrencyCode` varchar(255) DEFAULT NULL,
  `AccountDescriptiveName` varchar(255) DEFAULT NULL,
  `AccountTimeZone` varchar(255) DEFAULT NULL,
  `ActiveViewCpm` decimal(19,2) DEFAULT NULL,
  `ActiveViewCtr` decimal(19,2) DEFAULT NULL,
  `ActiveViewImpressions` bigint(20) DEFAULT NULL,
  `ActiveViewMeasurability` decimal(19,2) DEFAULT NULL,
  `ActiveViewMeasurableCost` decimal(19,2) DEFAULT NULL,
  `ActiveViewMeasurableImpressions` bigint(20) DEFAULT NULL,
  `ActiveViewViewability` decimal(19,2) DEFAULT NULL,
  `AdGroupAdDisapprovalReasons` varchar(255) DEFAULT NULL,
  `AdGroupAdTrademarkDisapproved` varchar(255) DEFAULT NULL,
  `AdGroupId` bigint(20) DEFAULT NULL,
  `AdGroupName` varchar(255) DEFAULT NULL,
  `AdGroupStatus` varchar(255) DEFAULT NULL,
  `AdNetworkType1` varchar(255) DEFAULT NULL,
  `AdNetworkType2` varchar(255) DEFAULT NULL,
  `AdType` varchar(255) DEFAULT NULL,
  `AllConversionRate` decimal(19,2) DEFAULT NULL,
  `AllConversionValue` decimal(19,2) DEFAULT NULL,
  `AllConversions` decimal(19,2) DEFAULT NULL,
  `AverageCost` decimal(19,2) DEFAULT NULL,
  `AverageCpc` decimal(19,2) DEFAULT NULL,
  `AverageCpe` decimal(19,2) DEFAULT NULL,
  `AverageCpm` decimal(19,2) DEFAULT NULL,
  `AverageCpv` decimal(19,2) DEFAULT NULL,
  `AveragePageviews` decimal(19,2) DEFAULT NULL,
  `AveragePosition` decimal(19,2) DEFAULT NULL,
  `AverageTimeOnSite` decimal(19,2) DEFAULT NULL,
  `BaseAdGroupId` bigint(20) DEFAULT NULL,
  `BaseCampaignId` bigint(20) DEFAULT NULL,
  `BounceRate` decimal(19,2) DEFAULT NULL,
  `BusinessName` varchar(255) DEFAULT NULL,
  `CallOnlyPhoneNumber` varchar(255) DEFAULT NULL,
  `CampaignId` bigint(20) DEFAULT NULL,
  `CampaignName` varchar(255) DEFAULT NULL,
  `CampaignStatus` varchar(255) DEFAULT NULL,
  `ClickAssistedConversionValue` decimal(19,2) DEFAULT NULL,
  `ClickAssistedConversions` bigint(20) DEFAULT NULL,
  `ClickAssistedConversionsOverLastClickConversions` decimal(19,2) DEFAULT NULL,
  `ClickType` varchar(255) DEFAULT NULL,
  `Clicks` bigint(20) DEFAULT NULL,
  `CombinedApprovalStatus` varchar(255) DEFAULT NULL,
  `ConversionCategoryName` varchar(255) DEFAULT NULL,
  `ConversionRate` decimal(19,2) DEFAULT NULL,
  `ConversionTrackerId` bigint(20) DEFAULT NULL,
  `ConversionTypeName` varchar(255) DEFAULT NULL,
  `ConversionValue` decimal(19,2) DEFAULT NULL,
  `Conversions` decimal(19,2) DEFAULT NULL,
  `Cost` decimal(19,2) DEFAULT NULL,
  `CostPerAllConversion` decimal(19,2) DEFAULT NULL,
  `CostPerConversion` decimal(19,2) DEFAULT NULL,
  `CostPerCurrentModelAttributedConversion` decimal(19,2) DEFAULT NULL,
  `CreativeApprovalStatus` varchar(255) DEFAULT NULL,
  `CreativeDestinationUrl` longtext,
  `CreativeFinalAppUrls` longtext,
  `CreativeFinalMobileUrls` longtext,
  `CreativeFinalUrls` longtext,
  `CreativeTrackingUrlTemplate` longtext,
  `CreativeUrlCustomParameters` longtext,
  `CriterionId` bigint(20) DEFAULT NULL,
  `CriterionType` varchar(255) DEFAULT NULL,
  `CrossDeviceConversions` decimal(19,2) DEFAULT NULL,
  `Ctr` decimal(19,2) DEFAULT NULL,
  `CurrentModelAttributedConversionValue` decimal(19,2) DEFAULT NULL,
  `CurrentModelAttributedConversions` decimal(19,2) DEFAULT NULL,
  `CustomerDescriptiveName` varchar(255) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `Description1` varchar(255) DEFAULT NULL,
  `Description2` varchar(255) DEFAULT NULL,
  `Device` varchar(255) DEFAULT NULL,
  `DevicePreference` bigint(20) DEFAULT NULL,
  `DisplayUrl` longtext,
  `EngagementRate` decimal(19,2) DEFAULT NULL,
  `Engagements` bigint(20) DEFAULT NULL,
  `EnhancedDisplayCreativeLogoImageMediaId` bigint(20) DEFAULT NULL,
  `EnhancedDisplayCreativeMarketingImageMediaId` bigint(20) DEFAULT NULL,
  `ExternalConversionSource` varchar(255) DEFAULT NULL,
  `GmailForwards` bigint(20) DEFAULT NULL,
  `GmailSaves` bigint(20) DEFAULT NULL,
  `GmailSecondaryClicks` bigint(20) DEFAULT NULL,
  `Headline` varchar(255) DEFAULT NULL,
  `HeadlinePart1` varchar(255) DEFAULT NULL,
  `HeadlinePart2` varchar(255) DEFAULT NULL,
  `Id` bigint(20) DEFAULT NULL,
  `ImageAdUrl` longtext,
  `ImageCreativeImageHeight` int(11) DEFAULT NULL,
  `ImageCreativeImageWidth` int(11) DEFAULT NULL,
  `ImageCreativeMimeType` int(11) DEFAULT NULL,
  `ImageCreativeName` varchar(255) DEFAULT NULL,
  `ImpressionAssistedConversionValue` decimal(19,2) DEFAULT NULL,
  `ImpressionAssistedConversions` bigint(20) DEFAULT NULL,
  `ImpressionAssistedConversionsOverLastClickConversions` decimal(19,2) DEFAULT NULL,
  `Impressions` bigint(20) DEFAULT NULL,
  `InteractionRate` decimal(19,2) DEFAULT NULL,
  `InteractionTypes` varchar(255) DEFAULT NULL,
  `Interactions` bigint(20) DEFAULT NULL,
  `IsNegative` varchar(255) DEFAULT NULL,
  `LabelIds` varchar(255) DEFAULT NULL,
  `Labels` varchar(255) DEFAULT NULL,
  `LongHeadline` varchar(255) DEFAULT NULL,
  `Path1` varchar(255) DEFAULT NULL,
  `Path2` varchar(255) DEFAULT NULL,
  `PercentNewVisitors` decimal(19,2) DEFAULT NULL,
  `PolicySummary` varchar(255) DEFAULT NULL,
  `PrimaryCompanyName` varchar(255) DEFAULT NULL,
  `ShortHeadline` varchar(255) DEFAULT NULL,
  `Slot` varchar(255) DEFAULT NULL,
  `Status` varchar(255) DEFAULT NULL,
  `Trademarks` varchar(255) DEFAULT NULL,
  `ValuePerAllConversion` decimal(19,2) DEFAULT NULL,
  `ValuePerConversion` decimal(19,2) DEFAULT NULL,
  `ValuePerCurrentModelAttributedConversion` decimal(19,2) DEFAULT NULL,
  `VideoQuartile100Rate` decimal(19,2) DEFAULT NULL,
  `VideoQuartile25Rate` decimal(19,2) DEFAULT NULL,
  `VideoQuartile50Rate` decimal(19,2) DEFAULT NULL,
  `VideoQuartile75Rate` decimal(19,2) DEFAULT NULL,
  `VideoViewRate` decimal(19,2) DEFAULT NULL,
  `VideoViews` bigint(20) DEFAULT NULL,
  `ViewThroughConversions` bigint(20) DEFAULT NULL,
  `AccentColor` varchar(255) DEFAULT NULL,
  `AllowFlexibleColor` varchar(255) DEFAULT NULL,
  `CallToActionText` varchar(255) DEFAULT NULL,
  `EnhancedDisplayCreativeLandscapeLogoImageMediaId` bigint(20) DEFAULT NULL,
  `EnhancedDisplayCreativeMarketingImageSquareMediaId` bigint(20) DEFAULT NULL,
  `FormatSetting` varchar(255) DEFAULT NULL,
  `MainColor` varchar(255) DEFAULT NULL,
  `PricePrefix` varchar(255) DEFAULT NULL,
  `PromoText` varchar(255) DEFAULT NULL,
  `Automated` varchar(255) DEFAULT NULL,
  `ConversionLagBucket` varchar(255) DEFAULT NULL,
  `CreativeFinalUrlSuffix` varchar(255) DEFAULT NULL,
  `GmailCreativeHeaderImageMediaId` bigint(20) DEFAULT NULL,
  `GmailCreativeLogoImageMediaId` bigint(20) DEFAULT NULL,
  `GmailCreativeMarketingImageMediaId` bigint(20) DEFAULT NULL,
  `GmailTeaserBusinessName` varchar(255) DEFAULT NULL,
  `GmailTeaserDescription` varchar(255) DEFAULT NULL,
  `GmailTeaserHeadline` varchar(255) DEFAULT NULL,
  `MarketingImageCallToActionText` varchar(255) DEFAULT NULL,
  `MarketingImageCallToActionTextColor` varchar(255) DEFAULT NULL,
  `MarketingImageDescription` varchar(255) DEFAULT NULL,
  `MarketingImageHeadline` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdAccentColor` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdAllowFlexibleColor` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdBusinessName` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdCallToActionText` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdDescriptions` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdDynamicSettingsPricePrefix` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdDynamicSettingsPromoText` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdFormatSetting` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdHeadlines` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdLandscapeLogoImages` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdLogoImages` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdLongHeadline` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdMainColor` varchar(255) DEFAULT NULL,
  `MultiAssetResponsiveDisplayAdMarketingImages` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`),
  KEY `reporting` (`ExternalCustomerId`,`Date`,`CampaignId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by nwbirnie** [comment]
Oh sorry, was doing some testing (managed to reproduce the same error).

Here's the missing column:   `MultiAssetResponsiveDisplayAdSquareMarketingImages` varchar(255) DEFAULT NULL,

**Comment by Timmeh74** [comment]
I just tried adding the column manually and got an error that might explain why it wasn't created in the first place:

```
ERROR 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs
```

From comparing your DDL to mine, I identified the following deprecated fields which did still exist in my database: 
```
AdGroupAdDisapprovalReasons
AdGroupAdTrademarkDisapproved
CreativeApprovalStatus
PrimaryCompanyName
Trademarks
```

After removing them, I was able to add the missing column _MultiAssetResponsiveDisplayAdSquareMarketingImages_.
During the comparison I found that my database was also missing the following fields:

```
ResponsiveSearchAdDescriptions
ResponsiveSearchAdHeadlines
ResponsiveSearchAdPath1
ResponsiveSearchAdPath2
SystemManagedEntitySource
```

I was able to create the four fields for the ResponsiveSearchAds manually, but as expected I get the same error as above (_Row size too large_) when trying to create the last column (cause I removed five fields and try to add six new ones).

So essentially this table has reached its maximum row size now and is still missing one field. It might be possible to add it as a TEXT instead of a VARCHAR (from what I read about row sizes in MySQL), but I'm not sure how that would affect AwReporting.
I also tried running AwReporting again and - as expected - I get the same error about a missing field, but now for _SystemManagedEntitySource_.

Any ideas?

**Comment by nwbirnie** [comment]
Running with TEXT should be fine on these new columns (particularly since you're not using them.) You can do this with `alter table AW_AdPerformanceReport modify <colname> TEXT;`. I just checked and on my install this preserves data and when Hibernate pushes the schema it doesn't revert the column type.

A quick calculation of the max row size on my machine is around 90kbits, or around 10kbytes, which is larger than the MySQL limit (65kbits) and the default InnoDB page size limit (8k).

Another option here would be to reinitialize the database for InnoDB 32k or 64k page sizes. This would mean having to migrate the data between instances, but would increase the row size limit across the board.

**Comment by Timmeh74** [comment]
I was able to add _SystemManagedEntitySource_ as a TEXT field and now AwReporting is working fine again. I'll keep it like this for now and consider moving the database to a new server with the recommended settings. Thanks for your support!
