### ISSUE TITLE
Problem with CAMPAIGN_LOCATION_TARGET_REPORT and "--" LocationId

### ISSUE THREAD

**Issue by madll** [googleads/aw-reporting#87]
Dear All, 

I'm facing an issue with the generation of the CAMPAIGN_LOCATION_TARGET_REPORT, this is happening since last month, where I started to notice Exceptions on the csv parsing stage of the report.

I guess it has something to do with some rows returning "--" as the LocationId (maybe are Unspecified Locations) and CSV trying to parse it as a Long and Failing with:

2014-11-03 12:05:45,692 [DEBUG|com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile|RunnableProcessorOnFile] ... success.
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NumberFormatException: Sign character in wrong position
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.api.ads.adwords.awreporting.processors.onfile.RunnableProcessorOnFile.run(RunnableProcessorOnFile.java:120)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: Sign character in wrong position
	at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:122)
	at com.google.api.ads.adwords.awreporting.model.util.CsvParserIterator.computeNext(CsvParserIterator.java:55)
	... 6 more
Caused by: java.lang.NumberFormatException: Sign character in wrong position
	at java.lang.Long.decode(Long.java:654)
	at com.sun.beans.editors.LongEditor.setAsText(LongEditor.java:45)
	at au.com.bytecode.opencsv.bean.CsvToBean.convertValue(CsvToBean.java:82)
	at com.google.api.ads.adwords.awreporting.model.util.ModifiedCsvToBean.processLine(ModifiedCsvToBean.java:102)
	... 7 more

I Also noticed that with GEO_PERFORMANCE_REPORT the ROW_IDS are not being unique generated maybe the problem it's related to the one above with the "--" LocationId:

org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: 
[com.google.api.ads.adwords.awreporting.model.entities.ReportGeo#XXXXXXX-YYYYY-ZZZZZ-20141029-20141031-Other----]

Thank you and best regards,

M.

**Comment by gustavo-moreira** [comment]
Hi madll,

this fix might solve this particular problem, but I believe there is a better approach to it.
Instead of putting a "0" as the ID, in this case the "--" means that there is no ID to the location. If this is a possible and valid case (which is the case in this report), we should do one of the following:
- Instead of "0" set the value as "NULL"
- Change the type of the property to String instead of Long.

The first approach might be a problem since all the values that are now being set as the String "--" will become NULL. This might brake queries from users that already rely on the "--" value.

I would say that changing the type of the field to String would be the more elegant solution, and more compliant with what is already being done.

Any thoughts before I change this?
Cheers.

**Comment by chenzhuo914** [comment]
I think we can just change the type from Long to String, and leave the values "--" untouched. This will keep aw-reporting simple and generic,  and not break users who are already depending on "--" values. And users are free to do post-processing to interpret "--" (such as converting it to null) according to their business needs.

**Comment by chenzhuo914** [comment]
Fixed in commit 9c648929d226189432d3f9cb6f9aa7f6e47cf73a.
